### ISSUE TITLE
Is this a framework for remote interaction with pornhub?

### ISSUE THREAD

**Issue by Veryed-VS** [buttplugio/stpihkal#103]
We are an app company that develops sex products. Now we need to connect with the remote interaction function of pornhub. Is this framework used? Can it be integrated into the app?

**Comment by qdot** [comment]
This particular repo is for documenting sex toy protocols, and has nothing to do with movie sync outside of documenting some of the known formats. 

Using Pornhub Interactive requires using FeelConnect, which is run by Kiiroo, so you'd have to contact them to discuss usage. You may also want to talk to SexLikeReal, who have their own video hosting platform with toy support.
