### ISSUE TITLE
Add WeVibe documentation

### ISSUE THREAD

**Issue by qdot** [buttplugio/stpihkal#20]
https://gist.github.com/bnm12/fcdcef291a500bf51cef734aa1830e4d

**Comment by blackspherefollower** [comment]
Vector (and probably Moxie) control scheme is marked as 8-bit enabled.

Vibrate: 0f03000X0Y0Z0000
  X=external vibe (3-f)
  Y=internal vibe (3-f)
  Z=on/off bitmask 1=internal 2=external. Note 0 does not stop both

Stop: 0f00000000000000
